<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Новинки сезона. Модные тренды и акции интернет-магазина KC-Shoes.ru </title>
</head>
<body>
<table style="margin:0; padding:15px 0 10px; width:100%; background-color:#eef2f5">
    <tr style="display: block; max-width: 600px; margin: 0 auto;">
        <td>
            <div style="margin-right:20px;">
                <a href="<?php echo $page_links['delivery'] ?>" style="margin:0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size:12px; text-transform:uppercase; text-decoration:none; color:#3697da">Доставка и оплата</a>
            </div>
        </td>
        <td>
            <div style="margin-right:215px;">
                <a href="<?php echo $page_links['about'] ?>" style="margin:0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size:12px; text-transform:uppercase; text-decoration:none; color:#3697da">о компании</a>
            </div>
        </td>
        <td>
            <img style="display:table-cell" src="https://kc-shoes.ru/catalog/view/theme/kcnew/image/header-phone.png">
        </td>
        <td>
            <p style="margin:0; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size:14px; font-weight:600; text-transform:uppercase; text-decoration:none; color:#3697da">8 800 700 27 68</p>
        </td>
    </tr>

</table>

<table style="margin:0; padding:0; width:100%; border-bottom:1px solid #d5dde3;">
    <tr>
        <td>
        </td>
        <td style="display: block; max-width: 600px; margin: 0 auto; clear: both;">
            <div style="padding:5px; max-width:600px; margin:0 auto; display: block;">
                <table bgcolor="#FFFFFF" style="margin:0; padding:0; width:100%">
                    <tr >
                        <td style="max-width:85px">
                            <a href="https://kc-shoes.ru/"  target="_blank"><img style="max-width: 100%; margin:0; padding:0;" src="https://kc-shoes.ru/image/data/Mail_send/e-21/logo.png" alt=""/></a>
                        </td>
                        <td>
                            <p style="padding-left:10px">
                                <a style="text-decoration: none;" href="<?php echo $page_links['woman_shoes'] ?>" target="_blank">
                                    <span style="color: #666666; font-weight: 500; font-size: 14px; font-family: 'Trebuchet MS', sans-serif; text-transform: uppercase; padding-left:5px; padding-right:5px;">Женщинам</span>
                                </a>
                                <a style="text-decoration: none;" href="<?php echo $page_links['man_shoes'] ?>" target="_blank">
                                    <span style="color: #666666; font-weight: 500; font-size: 14px; font-family: 'Trebuchet MS', sans-serif; text-transform: uppercase; padding-left:5px; padding-right:5px;">Мужчинам</span>
                                </a>
                                <a style="text-decoration: none;" href="<?php echo $page_links['bags'] ?>" target="_blank">
                                    <span style="color: #666666; font-weight: 500; font-size: 14px; font-family: 'Trebuchet MS', sans-serif; text-transform: uppercase; padding-left:5px; padding-right:5px;">Сумки</span>
                                </a>
                                <a style="text-decoration: none;" href="<?php echo $page_links['manufacturer'] ?>" target="_blank">
                                    <span style="color: #666666; font-weight: 500; font-size: 14px; font-family: 'Trebuchet MS', sans-serif; text-transform: uppercase; padding-left:5px; padding-right:5px;">Бренды</span>
                                </a>
                                <a style="text-decoration: none;" href="<?php echo $page_links['new'] ?>" target="_blank">
                                    <span style="color: #666666; font-weight: 500; font-size: 14px; font-family: 'Trebuchet MS', sans-serif; text-transform: uppercase; padding-left:5px; padding-right:5px;">Весна 2019</span>
                                </a>
                                <a style="text-decoration: none;" href="<?php echo $page_links['sale'] ?>" target="_blank">
                                    <span style="color: #666666; font-weight: 500; font-size: 14px; font-family: 'Trebuchet MS', sans-serif; text-transform: uppercase; padding-left:5px; padding-right:5px;">Распродажа</span>
                                </a>
                            </p>
                        </td>
                    </tr>
                </table>
            </div>
        </td>
        <td>
        </td>
    </tr>
</table>
<div style="max-width:600px; margin:0 auto; display: block">
<table border="0" cellpadding="40" cellspacing="0" height="0" width="100%" style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 28px; font-weight:bold;">
    <tbody>
		<tr>
			<td align="center" valign="middle">
				<div>
					Ваш заказ №<?php echo $order_id; ?> отправлен!
				</div>
			</td>
		</tr>
    </tbody>
</table>
</div>
<div style="max-width:600px; margin:0 auto; display: block">
	<table style="width:100%; background-color: #cbedff; height: 50px; margin-bottom:55px">
		<tr>
			<td style="display: block; max-width: 600px; margin: 0 auto; clear: both;">
			<!-- content -->
				<div style="padding: 5px; margin: 0 auto; display: block;">
					<table style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size:14px;color:#333333; line-height:20px;">
						<tr>
							<td>
								<p style="padding-left:15px;">
									Вы можете отследить заказ по <a href="https://kc-shoes.ru/services/otslezhivanie/?post_no=<?php echo $post_no; ?>" style="text-decoration: none; color:#1f739f;">этой ссылке</a>
								</p>
								<p style="padding-left:15px;">
									Мы готовы ответить на ваши вопросы по электронной почте <strong style="font-size:15px;">info@kc-shoes.ru</strong>
									или по телефону <strong style="font-size:15px;">8 (800) 700-27-68</strong> (звонок бесплатный)
								</p>
							</td>
						</tr>
					</table>
				</div>
			<!-- /content -->
			</td>
			<td>
			</td>
		</tr>
	</table>
</div>

<table style="width:100%; background-color: #cbedff; height: 50px; margin-bottom:5px; margin-top: 150px;">
    <tr>
        <td style="display: block; max-width: 600px; margin: 0 auto; clear: both;">
            <!-- content -->
            <div style="padding: 5px; margin: 0 auto; display: block;">
                <table style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; color:#333333; text-transform:uppercase">
                    <tr>
                        <td height="25" align="center" style="display:table-cell; margin:0px; margin-top:10px; padding-right:5px; font-size:14px;">
                            <img style="vertical-align:top;border:none" src="https://kc-shoes.ru/catalog/view/theme/kcnew/image/email-img.png" height="20x">
                        </td>
                        <td height="25" align="center" style="display:table-cell; margin:0px; margin-top:10px; padding-right:15px; font-size:14px; color:#1f739f;">
                            kc-shoes@mail.ru
                        </td>
                        <!-- <td width="10px" style="border-left:1px solid white;">
                        </td> -->
                        <td height="25" align="center" style="display:table-cell; border-left:1px solid white; margin:0px; margin-top:10px; padding-left:20px; margin-right:10px; font-size:14px;">
                            Присоединяйтесь:
                        </td>
                        <td height="25" style="display:table-cell; margin:0px">
                            <a href="https://vk.com/kcshoes" target="_blank" rel="noopener"><img style="vertical-align:top;border:none" src="https://kc-shoes.ru/image/email/vk.png" height="25px"></a>
                        </td>
                        <td height="25" style="display:table-cell; margin:0px">
                            <a href="https://www.instagram.com/kcshoes.ru/" target="_blank" rel="noopener"><img style="vertical-align:top;border:none" src="https://kc-shoes.ru/image/email/in.png" height="25px"></a>
                        </td>
                        <td height="25" style="display:table-cell; margin:0px">
                            <a href="https://ok.ru/kcshoes.r" target="_blank" rel="noopener"><img style="vertical-align:top;border:none" src="https://kc-shoes.ru/image/email/ok.png" height="25px"></a>
                        </td>
                    </tr>
                </table>
            </div>
            <!-- /content -->
        </td>
        <td>
        </td>
    </tr>
</table>
<table style="margin:0; padding:15px 0 10px; width:100%; background-color:#cbedff; font-family:'Helvetica Neue',Helvetica,Arial,sans-serif; font-size:13px;">
	<tr style="display: block; max-width: 600px; margin: 0 auto; margin-bottom:10px;">
		<td width="140px">
			<div style="margin-right:20px;">
				<a href="" style="display:inline-block; text-decoration:none; color:#666666">Доставка и оплата</a>
			</div>
		</td>
		<td width="110px">
			<div style="margin-right:20px;">
				<a href="" style="display:inline-block; text-decoration:none; color:#666666">Отслеживание</a>
			</div>
		</td>
		<td width="80px">
			<div style="margin-right:20px;">
				<a href="" style="display:inline-block; text-decoration:none; color:#666666">Отзывы</a>
			</div>
		</td>
		<td width="80px">
			<div style="margin-right:20px;">
				<a href="" style="display:inline-block; text-decoration:none; color:#666666">Акции</a>
			</div>
		</td>
		<td>
			<div style="margin-right:20px;">
				<a href="" style="display:inline-block; text-decoration:none; color:#666666">Оферта</a>
			</div>
		</td>
	</tr>
	<tr style="display: block; max-width: 600px; margin: 0 auto; margin-bottom: 80px">
		<td width="140px">
			<div style="margin-right:20px;">
				<a href="" style="display:inline-block; text-decoration:none; color:#666666">Возврат</a>
			</div>
		</td>
		<td width="110px">
			<div style="margin-right:20px;">
				<a href="" style="display:inline-block; text-decoration:none; color:#666666">О компании</a>
			</div>
		</td>
		<td width="80px">
			<div style="margin-right:20px;">
				<a href="" style="display:inline-block; text-decoration:none; color:#666666">Новости</a>
			</div>
		</td>
		<td>
			<div style="margin-right:20px;">
				<a href="" style="display:inline-block; text-decoration:none; color:#666666">Контакты</a>
			</div>
		</td>
	</tr>
</table>


</body>
</html>
